# Generated by Django 4.2.6 on 2023-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_logindetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
