# Generated by Django 4.2.6 on 2023-10-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='login',
        ),
    ]
