# Generated by Django 4.2.6 on 2023-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_details_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logindata',
        ),
    ]
